services:
  db:
    image: postgres:15.1
    environment:
      POSTGRES_USER: bduff9
      POSTGRES_PASSWORD: bduff9
      POSTGRES_DB: fitr
    ports:
      - "5432:5432"
    volumes:
      - ./docker/data:/var/lib/postgresql/data

  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - "8080:8080"
